### ISSUE TITLE
Error in link.particles

### ISSUE THREAD

**Issue by dmattek** [federicomarini/flowcatchR#1]
I'm going through [the guide](http://bioconductor.org/packages/release/bioc/vignettes/flowcatchR/inst/doc/flowcatchr_vignette.html#6_particle_tracking) and ran `preprocess.Frames` with `at.offset=0.65`.  This produces fewer and smaller objects. The `link.particles` crashes in the first frame with the error:

> `Error in Xcand[ic] <- which(A[Icand[ic], ] == 1) :  replacement has length zero`

The same happens in the shiny app already with default dataset and parameters:

> `Warning: Error in <-: replacement has length zero`
> `187: link.particles`
> ` 186: <reactive:trajData> [/home/user/R/3.6/library/flowcatchR/shiny/server.R#78]`

**Comment by federicomarini** [comment]
Hi @dmattek! 

Well this is actual two things

- for the first issue: you are selecting a too hi value for the threshold, so it is to be expected that the objects are not detected correctly. And as a consequence, the tracking algorithm end up failing as it does not detect the particles in a meaningful way

- for the second, in the shiny app there is a different setting, where `include.area` is set as default to TRUE. If you switch to FALSE, the trajectories appear correctly. I'll fix this and change the default value to FALSE, thanks for the catch!

**Comment by dmattek** [comment]
> you are selecting a too hi value for the threshold, so it is to be expected that the objects are not detected correctly. And as a consequence, the tracking algorithm end up failing as it does not detect the particles in a meaningful way

Yes, I realise that. I did it to simulate a situation that I am dealing with in my dataset. I have very few (1-2) objects in a field of view and objects appear only for a couple of frames. Most of the time, there are no objects at all. Thus, I was wondering whether your implementation of the linking algorithm would be suitable for such problems.

**Comment by federicomarini** [comment]
Good question.
Given the fact that this algorithm is strongly based on the _evergreen_ of Sbalzarini and Komoutsakos, I would say that it can be applied to a wide variety of situations.

In your case, I wonder whether the automated tracking is the best solution: if there are so few objects, and so rarely, maybe a manual approach is the one that will serve you best. Yet I can appreciate your effort to make the entire processing with no manual intervention, which is the best approach for obtaining reproducible and objective results.

That said: I can not judge whether the algorithm is not "fooled" by the sparsity of the objects. Fact is the way it is implemented expects some objects to be found "every now and then", and this is not happening, therefore the error message.

Hope this helps 😉
Federico
